spring:
  application:
    name: event-interface

  kafka:
    bootstrap-servers: ${kafka.bootstrap-servers:localhost:9092}
    #bootstrap-servers: localhost:9092

  datasource:
    url: "jdbc:mysql://cdmplite-dev.cwpogff1ae9e.us-west-2.rds.amazonaws.com:3306/cdmp_dev"
    username: "cdmpadmin"
    password: "CdmpL!t3"

  hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"

